http:
  routers:
    # Individual Services
    homeassistant:
      rule: "Host(`hass.${DOMAIN}`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker
  services:
    # Individual Services
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://${HOMEASSISTANT_IP}:8123"
        passHostHeader: true
