# Dokuwiki - Self-hosted Wiki Platform
# Place in /opt/stacks/productivity/dokuwiki/docker-compose.yml

services:
  dokuwiki:
    image: lscr.io/linuxserver/dokuwiki:latest
    container_name: dokuwiki
    restart: unless-stopped
    networks:
      - traefik-network
    ports:
      - "80:80"
    volumes:
      - ./config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    labels:
      - "homelab.category=productivity"
      - "homelab.description=Self-hosted wiki platform"
      - "traefik.enable=true"
      - "traefik.http.routers.dokuwiki.rule=Host(`wiki.${DOMAIN}`)"
      - "traefik.http.routers.dokuwiki.entrypoints=websecure"
      - "traefik.http.routers.dokuwiki.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dokuwiki.middlewares=authelia@docker"
      - "traefik.http.services.dokuwiki.loadbalancer.server.port=80"
      - "x-dockge.url=https://wiki.${DOMAIN}"

volumes:
  dokuwiki-config:

networks:
  traefik-network:
    external: true