###############################################################
#                         Users Database                      #
###############################################################

users:
  ${DEFAULT_USER}:
    displayname: "Admin User"
    password: "${AUTHELIA_ADMIN_PASSWORD_HASH}"
    email: ${DEFAULT_EMAIL}
    groups:
      - admins
      - users
