###############################################################
#                         Users Database                      #
###############################################################

users:
  admin:
    displayname: "admin"
    password: "generate-with-openssl-rand-hex-64"
    email: admin@example.com
    groups:
      - admins
      - users
