###############################################################
#                         Users Database                      #
###############################################################

users:
  kelin:
    displayname: "kelin"
    password: "$argon2id$v=19$m=65536,t=3,p=4$e97MzVuvteD5VfHT+Kw9Ew$NnK63ABYKRm5d8nWG7Z8dbRBJfhhHjaf71zQ354KSN4"
    email: kelinshomelab@gmail.com
    groups:
      - admins
      - users
