http:
  routers:
    # Individual Services
    homeassistant:
      rule: "Host(`hass.kelinreij.duckdns.org`)"
      entryPoints:
        - websecure
      service: homeassistant
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker
  services:
    # Individual Services
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://:8123"
        passHostHeader: true
