http:
  routers:
# Remote Server Services (your-remote-server)
    dockge-your-remote-server:
      rule: "Host(`dockge.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: dockge-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    dozzle-your-remote-server:
      rule: "Host(`dozzle.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: dozzle-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    glances-your-remote-server:
      rule: "Host(`glances.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: glances-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    backrest-your-remote-server:
      rule: "Host(`backrest.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: backrest-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    duplicati-your-remote-server:
      rule: "Host(`duplicati.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: duplicati-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    homepage-your-remote-server:
      rule: "Host(`homepage.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: homepage-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    homarr-your-remote-server:
      rule: "Host(`homarr.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: homarr-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    grafana-your-remote-server:
      rule: "Host(`grafana.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: grafana-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    prometheus-your-remote-server:
      rule: "Host(`prometheus.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: prometheus-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

    uptime-kuma-your-remote-server:
      rule: "Host(`status.your-remote-server.yourdomain.duckdns.org`)"
      entryPoints:
        - websecure
      service: uptime-kuma-your-remote-server
      tls:
        certResolver: letsencrypt
      middlewares:
        - authelia@docker

# Service Definitions
  services:
    backrest-jasper:
      loadBalancer:
        servers:
          - url: "http://192.168.4.4:9898"
        passHostHeader: true

    vaultwarden-jasper:
      loadBalancer:
        servers:
          - url: "http://192.168.4.4:8091"
        passHostHeader: true

    bookstack-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:6875"
        passHostHeader: true

    calibre-web-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8083"
        passHostHeader: true

    code-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8079"
        passHostHeader: true

    dockge-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:5001"
        passHostHeader: true

    dockhand-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:3003"
        passHostHeader: true

    dokuwiki-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8087"
        passHostHeader: true

    dozzle-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8085"
        passHostHeader: true

    duplicati-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8200"
        passHostHeader: true

    ez-assistant-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:18789"  # Internal IP of jasper server
        passHostHeader: true

    formio-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:3002"
        passHostHeader: true

    gitea-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:3010"
        passHostHeader: true

    glances-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:61208"
        passHostHeader: true

    homarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:7575"
        passHostHeader: true

    homepage-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:3000"
        passHostHeader: true

    jellyfin-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8096"
        passHostHeader: true

    jupyter-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8890"
        passHostHeader: true

    kopia-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:51515"
        passHostHeader: true

    mealie-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:9000"
        passHostHeader: true

    mediawiki-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8086"
        passHostHeader: true

    motioneye-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8081"
        passHostHeader: true

    nextcloud-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8089"
        passHostHeader: true

    openkm-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:18080"
        passHostHeader: true

    openwebui-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:3000"
        passHostHeader: true

    qbittorrent-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8081"
        passHostHeader: true

    tdarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8265"
        passHostHeader: true

    unmanic-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8889"
        passHostHeader: true

    wordpress-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8088"
        passHostHeader: true

    # Arr Services

    jellyseerr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:5055"
        passHostHeader: true

    prowlarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:9696"
        passHostHeader: true

    radarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:7878"
        passHostHeader: true

    sonarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8989"
        passHostHeader: true

    lidarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8686"
        passHostHeader: true

    readarr-jasper:
      loadbalancer:
        servers:
          - url: "http://192.168.4.4:8787"
        passHostHeader: true

    mylar3-jasper:
      loadBalancer:
        servers:
          - url: "http://192.168.4.4:8090"
        passHostHeader: true




# Remote Server Service Definitions (your-remote-server)
    dockge-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:5001"
        passHostHeader: true

    dozzle-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:8085"
        passHostHeader: true

    glances-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:61208"
        passHostHeader: true

    backrest-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:9898"
        passHostHeader: true

    duplicati-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:8200"
        passHostHeader: true

    homepage-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:3000"
        passHostHeader: true

    homarr-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:7575"
        passHostHeader: true

    grafana-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:3000"
        passHostHeader: true

    prometheus-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:9090"
        passHostHeader: true

    uptime-kuma-your-remote-server:
      loadbalancer:
        servers:
          - url: "http://your.remote.ip.address:3001"
        passHostHeader: true

# Middleware Definitions
  middlewares:
    ez-assistant-websocket:
      headers:
        accessControlAllowHeaders:
          - "Connection"
          - "Upgrade"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "OPTIONS"
        accessControlMaxAge: 86400
