# Session duration set to 5m for testing. Increase to 30m for production.
http:
  middlewares:
    authelia:
      forwardauth:
        address: http://authelia:9091/api/verify?rd=https://auth.yourdomain.duckdns.org/
        authResponseHeaders:
          - X-Secret
        trustForwardHeader: true

    sablier-jasper-arr:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-arr
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Arr Apps
            theme: ghost
            show-details-by-default: true

    sablier-jasper-backrest:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-backrest
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Backrest
            theme: ghost
            show-details-by-default: true

    sablier-jasper-vaultwarden:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-vaultwarden
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Vaultwarden
            theme: ghost
            show-details-by-default: true

    sablier-jasper-bookstack:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-bookstack
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Bookstack
            theme: ghost
            show-details-by-default: true

    sablier-jasper-calibre-web:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-calibre-web
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Calibre Web
            theme: ghost
            show-details-by-default: true

    sablier-jasper-code-server:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-code-server
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Code Server
            theme: ghost
            show-details-by-default: true

    sablier-jasper-dozzle:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-dozzle
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: dozzle
            theme: ghost
            show-details-by-default: true

    sablier-jasper-dokuwiki:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-dokuwiki
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: DokuWiki
            theme: ghost
            show-details-by-default: true

    sablier-jasper-duplicati:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-duplicati
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Duplicati
            theme: ghost
            show-details-by-default: true

    sablier-jasper-assistant:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-assistant
          sessionDuration: 30m
          ignoreUserAgent: curl
          dynamic:
            displayName: EZ-Assistant
            theme: ghost
            show-details-by-default: true

    sablier-jasper-formio:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-formio
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: FormIO
            theme: ghost
            show-details-by-default: true

    sablier-jasper-gitea:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-gitea
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Gitea
            theme: ghost
            show-details-by-default: true

    sablier-jasper-glances:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-glances
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Glances
            theme: ghost
            show-details-by-default: true

    sablier-jasper-homarr:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-homarr
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Homarr
            theme: ghost
            show-details-by-default: true

    sablier-jasper-jellyfin:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-jellyfin
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Jellyfin
            theme: ghost
            show-details-by-default: true

    sablier-jasper-jupyter:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-jupyter
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Jupyter
            theme: ghost
            show-details-by-default: true

    sablier-jasper-komodo:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-komodo
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Komodo
            theme: ghost
            show-details-by-default: true

    sablier-jasper-kopia:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-kopia
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Kopia
            theme: ghost
            show-details-by-default: true

    sablier-jasper-mealie:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-mealie
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Mealie
            theme: ghost
            show-details-by-default: true

    sablier-jasper-mediawiki:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-mediawiki
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: mediawiki
            theme: ghost
            show-details-by-default: true

    sablier-jasper-nextcloud:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-nextcloud
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: NextCloud
            theme: ghost
            show-details-by-default: true

    sablier-jasper-openkm:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-openkm
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: OpenKM
            theme: ghost
            show-details-by-default: true

    sablier-jasper-openwebui:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-openwebui
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: OpenWebUI
            theme: ghost
            show-details-by-default: true

    sablier-jasper-pulse:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-pulse
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Pulse
            theme: ghost
            show-details-by-default: true

    sablier-jasper-tdarr:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-tdarr
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Tdarr
            theme: ghost
            show-details-by-default: true

    sablier-jasper-unmanic:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-unmanic
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Unmanic
            theme: ghost
            show-details-by-default: true

    sablier-jasper-wordpress:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: jasper-wordpress
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: wordpress
            theme: ghost
            show-details-by-default: true

    # Remote Server (your-remote-server) Sablier Middlewares
    sablier-your-remote-server-dockge:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-dockge
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Dockge (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-dozzle:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-dozzle
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Dozzle (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-glances:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-glances
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Glances (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-backrest:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-backrest
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Backrest (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-duplicati:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-duplicati
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Duplicati (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-homepage:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-homepage
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Homepage (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-homarr:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-homarr
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Homarr (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-grafana:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-grafana
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Grafana (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-prometheus:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-prometheus
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Prometheus (your-remote-server)
            theme: ghost
            show-details-by-default: true

    sablier-your-remote-server-uptime-kuma:
      plugin:
        sablier:
          sablierUrl: http://sablier-service:10000
          group: your-remote-server-uptime-kuma
          sessionDuration: 5m
          ignoreUserAgent: curl
          dynamic:
            displayName: Uptime Kuma (your-remote-server)
            theme: ghost
            show-details-by-default: true
