---
# Currently Installed Services - Grouped by Stack

- Dashboards:
    - Homepage:
        icon: homepage.png
        href: https://homepage.${DOMAIN}
        description: This Dashboard
        container: homepage

    - Homarr:
        icon: homarr.png
        href: https://homarr.${DOMAIN}
        description: Alternative Dashboard
        container: homarr

- Core:
    - Dockge:
        icon: dockge.png
        href: https://dockge.${SERVER_HOSTNAME}.${DOMAIN}
        description: Docker Compose Manager
        container: dockge

    - Traefik:
        icon: traefik.png
        href: https://traefik.${DOMAIN}
        description: Reverse Proxy & SSL
        container: traefik

    - Authelia:
        icon: authelia.png
        href: https://auth.${DOMAIN}
        description: Authentication Portal
        container: authelia

- Infrastructure:
    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.${SERVER_HOSTNAME}.${DOMAIN}
        description: Real-time Log Viewer
        container: dozzle

    - Glances:
        icon: glances.png
        href: https://glances.${SERVER_HOSTNAME}.${DOMAIN}
        description: System Monitoring
        container: glances

    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.${DOMAIN}
        description: Network-wide Ad Blocking
        container: pihole

# Available to Install - Grouped by Stack

- Media:
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.${DOMAIN}
        description: Open Source Media Server
        container: jellyfin

    - Jellyseerr:
        icon: jellyseerr.png
        href: https://jellyseerr.${DOMAIN}
        description: Media Request Manager
        container: jellyseerr

    - Calibre-Web:
        icon: calibre-web.png
        href: https://calibre.${DOMAIN}
        description: Ebook Library
        container: calibre-web

- Media Management:
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.${DOMAIN}
        description: TV Shows Automation
        container: sonarr

    - Radarr:
        icon: radarr.png
        href: https://radarr.${DOMAIN}
        description: Movies Automation
        container: radarr

    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.${DOMAIN}
        description: Indexer Manager
        container: prowlarr

    - Readarr:
        icon: readarr.png
        href: https://readarr.${DOMAIN}
        description: Books Automation
        container: readarr

    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.${DOMAIN}
        description: Music Automation
        container: lidarr

    - Mylar3:
        icon: mylar.png
        href: https://mylar.${DOMAIN}
        description: Comics Manager
        container: mylar3

    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbit.${DOMAIN}
        description: Torrent Client
        container: qbittorrent

    - Tdarr:
        icon: tdarr.png
        href: https://tdarr.${DOMAIN}
        description: Media Transcoding
        container: tdarr

- Home Automation:
    - Home Assistant:
        icon: home-assistant.png
        href: https://ha.${DOMAIN}
        description: Home Automation Platform
        container: homeassistant

    - ESPHome:
        icon: esphome.png
        href: https://esphome.${DOMAIN}
        description: ESP Device Manager
        container: esphome

    - Node-RED:
        icon: node-red.png
        href: https://nodered.${DOMAIN}
        description: Flow-based Automation
        container: nodered

    - Zigbee2MQTT:
        icon: zigbee2mqtt.png
        href: https://zigbee.${DOMAIN}
        description: Zigbee Bridge
        container: zigbee2mqtt

    - Mosquitto:
        icon: mosquitto.png
        href: https://mqtt.${DOMAIN}
        description: MQTT Broker
        container: mosquitto

- Productivity:
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.${DOMAIN}
        description: Cloud Storage & Collaboration
        container: nextcloud

    - Gitea:
        icon: gitea.png
        href: https://gitea.${DOMAIN}
        description: Git Repository
        container: gitea

    - Mealie:
        icon: mealie.png
        href: https://mealie.${DOMAIN}
        description: Recipe Manager
        container: mealie

    - WordPress:
        icon: wordpress.png
        href: https://wordpress.${DOMAIN}
        description: CMS Platform
        container: wordpress

- Wikis:
    - BookStack:
        icon: bookstack.png
        href: https://bookstack.${DOMAIN}
        description: Wiki Platform
        container: bookstack

    - DokuWiki:
        icon: dokuwiki.png
        href: https://dokuwiki.${DOMAIN}
        description: Simple Wiki
        container: dokuwiki

    - MediaWiki:
        icon: mediawiki.png
        href: https://mediawiki.${DOMAIN}
        description: Wikipedia Engine
        container: mediawiki

- Monitoring Stack:
    - Grafana:
        icon: grafana.png
        href: https://grafana.${DOMAIN}
        description: Metrics Dashboard
        container: grafana

    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.${DOMAIN}
        description: Metrics Collection
        container: prometheus

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://uptime-kuma.${DOMAIN}
        description: Uptime Monitoring
        container: uptime-kuma
        
    - cAdvisor:
        icon: cadvisor.png
        href: https://cadvisor.${DOMAIN}
        description: Container Metrics
        container: cadvisor

- Development:
    - VS Code Server:
        icon: vscode.png
        href: https://code.${DOMAIN}
        description: Browser-based IDE
        container: code-server

    - Jupyter:
        icon: jupyter.png
        href: https://jupyter.${DOMAIN}
        description: Data Science Notebooks
        container: jupyter

- Backups:
    - Backrest:
        icon: mdi-backup-restore
        href: https://backrest.${DOMAIN}
        description: Backup Solution
        container: backrest

    - Duplicati:
        icon: duplicati.png
        href: https://duplicati.${DOMAIN}
        description: Backup Software
        container: duplicati

- Utilities:
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vault.${DOMAIN}
        description: Password Manager
        container: vaultwarden

    - Formio:
        icon: mdi-form-select
        href: https://formio.${DOMAIN}
        description: Form Builder
        container: formio

- Alternatives:
    - Portainer:
        icon: portainer.png
        href: https://portainer.${DOMAIN}
        description: Container Management UI
        container: portainer

    - Authentik:
        icon: authentik.png
        href: https://authentik.${DOMAIN}
        description: Alternative Auth Provider
        container: authentik

    - Plex:
        icon: plex.png
        href: https://plex.${DOMAIN}
        description: Media Server
        container: plex