---
# Currently Installed Services - Grouped by Stack

- Core Stack (core.yml):
    - Traefik:
        icon: traefik.png
        href: https://traefik.{{HOMEPAGE_VAR_DOMAIN}}
        description: Reverse Proxy & SSL
        
    - Authelia:
        icon: authelia.png
        href: https://auth.{{HOMEPAGE_VAR_DOMAIN}}
        description: Authentication Portal

- Infrastructure Stack (infrastructure.yml):
    - Dockge:
        icon: dockge.png
        href: https://dockge.{{HOMEPAGE_VAR_DOMAIN}}
        description: Docker Compose Manager
        
    - Dozzle:
        icon: dozzle.png
        href: https://dozzle.{{HOMEPAGE_VAR_DOMAIN}}
        description: Real-time Log Viewer
        
    - Glances:
        icon: glances.png
        href: https://glances.{{HOMEPAGE_VAR_DOMAIN}}
        description: System Monitoring
        
    - Pi-hole:
        icon: pi-hole.png
        href: https://pihole.{{HOMEPAGE_VAR_DOMAIN}}
        description: Network-wide Ad Blocking

- Dashboards Stack (dashboards.yml):
    - Homepage:
        icon: homepage.png
        href: https://home.{{HOMEPAGE_VAR_DOMAIN}}
        description: This Dashboard
        
    - Homarr:
        icon: homarr.png
        href: https://homarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Alternative Dashboard

- Alternatives Stack (alternatives.yml):
    - Portainer:
        icon: portainer.png
        href: https://portainer.{{HOMEPAGE_VAR_DOMAIN}}
        description: Container Management UI
        
    - Authentik:
        icon: authentik.png
        href: https://authentik.{{HOMEPAGE_VAR_DOMAIN}}
        description: Alternative Auth Provider

# Available to Install - Grouped by Stack

- Media Stack (media.yml):
    - Plex:
        icon: plex.png
        href: https://plex.{{HOMEPAGE_VAR_DOMAIN}}
        description: Media Server
        
    - Jellyfin:
        icon: jellyfin.png
        href: https://jellyfin.{{HOMEPAGE_VAR_DOMAIN}}
        description: Open Source Media Server
        
    - Sonarr:
        icon: sonarr.png
        href: https://sonarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: TV Shows Automation
        
    - Radarr:
        icon: radarr.png
        href: https://radarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Movies Automation
        
    - Prowlarr:
        icon: prowlarr.png
        href: https://prowlarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Indexer Manager
        
    - qBittorrent:
        icon: qbittorrent.png
        href: https://qbit.{{HOMEPAGE_VAR_DOMAIN}}
        description: Torrent Client

- Media Management Stack (media-management.yml):
    - Readarr:
        icon: readarr.png
        href: https://readarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Books Automation
        
    - Lidarr:
        icon: lidarr.png
        href: https://lidarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Music Automation
        
    - Mylar3:
        icon: mylar.png
        href: https://mylar.{{HOMEPAGE_VAR_DOMAIN}}
        description: Comics Manager
        
    - Calibre-Web:
        icon: calibre-web.png
        href: https://calibre.{{HOMEPAGE_VAR_DOMAIN}}
        description: Ebook Library
        
    - Jellyseerr:
        icon: jellyseerr.png
        href: https://jellyseerr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Media Request Manager
        
    - Tdarr:
        icon: tdarr.png
        href: https://tdarr.{{HOMEPAGE_VAR_DOMAIN}}
        description: Media Transcoding

- Home Automation Stack (homeassistant.yml):
    - Home Assistant:
        icon: home-assistant.png
        href: https://ha.{{HOMEPAGE_VAR_DOMAIN}}
        description: Home Automation Platform
        
    - ESPHome:
        icon: esphome.png
        href: https://esphome.{{HOMEPAGE_VAR_DOMAIN}}
        description: ESP Device Manager
        
    - Node-RED:
        icon: node-red.png
        href: https://nodered.{{HOMEPAGE_VAR_DOMAIN}}
        description: Flow-based Automation
        
    - Zigbee2MQTT:
        icon: zigbee2mqtt.png
        href: https://zigbee.{{HOMEPAGE_VAR_DOMAIN}}
        description: Zigbee Bridge
        
    - Mosquitto:
        icon: mosquitto.png
        href: https://mqtt.{{HOMEPAGE_VAR_DOMAIN}}
        description: MQTT Broker

- Productivity Stack (productivity.yml):
    - Nextcloud:
        icon: nextcloud.png
        href: https://nextcloud.{{HOMEPAGE_VAR_DOMAIN}}
        description: Cloud Storage & Collaboration
        
    - Gitea:
        icon: gitea.png
        href: https://gitea.{{HOMEPAGE_VAR_DOMAIN}}
        description: Git Repository
        
    - Mealie:
        icon: mealie.png
        href: https://mealie.{{HOMEPAGE_VAR_DOMAIN}}
        description: Recipe Manager
        
    - BookStack:
        icon: bookstack.png
        href: https://bookstack.{{HOMEPAGE_VAR_DOMAIN}}
        description: Wiki Platform
        
    - DokuWiki:
        icon: dokuwiki.png
        href: https://dokuwiki.{{HOMEPAGE_VAR_DOMAIN}}
        description: Simple Wiki
        
    - WordPress:
        icon: wordpress.png
        href: https://wordpress.{{HOMEPAGE_VAR_DOMAIN}}
        description: CMS Platform

- Monitoring Stack (monitoring.yml):
    - Grafana:
        icon: grafana.png
        href: https://grafana.{{HOMEPAGE_VAR_DOMAIN}}
        description: Metrics Dashboard
        
    - Prometheus:
        icon: prometheus.png
        href: https://prometheus.{{HOMEPAGE_VAR_DOMAIN}}
        description: Metrics Collection
        
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://uptime.{{HOMEPAGE_VAR_DOMAIN}}
        description: Uptime Monitoring
        
    - Loki:
        icon: loki.png
        href: https://loki.{{HOMEPAGE_VAR_DOMAIN}}
        description: Log Aggregation
        
    - cAdvisor:
        icon: cadvisor.png
        href: https://cadvisor.{{HOMEPAGE_VAR_DOMAIN}}
        description: Container Metrics

- Development Stack (development.yml):
    - VS Code Server:
        icon: vscode.png
        href: https://code.{{HOMEPAGE_VAR_DOMAIN}}
        description: Browser-based IDE
        
    - GitLab:
        icon: gitlab.png
        href: https://gitlab.{{HOMEPAGE_VAR_DOMAIN}}
        description: DevOps Platform
        
    - Jupyter:
        icon: jupyter.png
        href: https://jupyter.{{HOMEPAGE_VAR_DOMAIN}}
        description: Data Science Notebooks
        
    - pgAdmin:
        icon: pgadmin.png
        href: https://pgadmin.{{HOMEPAGE_VAR_DOMAIN}}
        description: PostgreSQL Admin

- Utilities Stack (utilities.yml):
    - Backrest:
        icon: mdi-backup-restore
        href: https://backrest.{{HOMEPAGE_VAR_DOMAIN}}
        description: Backup Solution
        
    - Duplicati:
        icon: duplicati.png
        href: https://duplicati.{{HOMEPAGE_VAR_DOMAIN}}
        description: Backup Software
        
    - Vaultwarden:
        icon: vaultwarden.png
        href: https://vault.{{HOMEPAGE_VAR_DOMAIN}}
        description: Password Manager
        
    - Formio:
        icon: mdi-form-select
        href: https://formio.{{HOMEPAGE_VAR_DOMAIN}}
        description: Form Builder
