###############################################################
#                         Users Database                      #
###############################################################

users:
  ${AUTHELIA_ADMIN_USER}:
    displayname: "${AUTHELIA_ADMIN_USER}"
    password: "${AUTHELIA_ADMIN_PASSWORD_HASH}"
    email: ${AUTHELIA_ADMIN_EMAIL}
    groups:
      - admins
      - users
